# Generated by Django 6.0.2 on 2026-02-23 23:41

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(help_text='Imagen del avatar', upload_to='avatars/')),
                ('is_default', models.BooleanField(default=False, help_text='Si es un avatar disponible para todos al inicio')),
                ('unlock_condition_description', models.TextField(blank=True, help_text='Descripción de cómo desbloquearlo si no es default', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre de la insignia', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Descripción de lo que se necesita para obtenerla')),
                ('image', models.ImageField(blank=True, help_text='Imagen de la insignia', null=True, upload_to='badges/')),
                ('category', models.CharField(choices=[('BASIC', 'Básica'), ('RARE', 'Rara'), ('EPIC', 'Épica'), ('LEGENDARY', 'Legendaria')], default='BASIC', max_length=20)),
                ('condition_description', models.TextField(help_text="Descripción legible de la condición (e.g., 'Acertar 10 slangs')")),
                ('unlock_condition_data', models.JSONField(blank=True, default=list, help_text="Lista de objetos de condición (e.g., [{'type': 'correct_slangs', 'value': 10}])")),
                ('reward_description', models.TextField(help_text="Descripción de la recompensa (e.g., '+30 EXP, Nuevo Avatar')")),
                ('reward_data', models.JSONField(blank=True, default=dict, help_text="Datos programáticos para las recompensas (e.g., {'exp': 30, 'avatar_id': 5})")),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre'}, max_length=150, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'Correo electrónico ya existe'}, max_length=254, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('SURVIVOR', 'Survivor RPG (Godot)'), ('QUIZ', 'Lección Interactiva (React)')], default='QUIZ', max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('correct_in_game', models.IntegerField(default=0)),
                ('total_questions_in_game', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/')),
                ('verified', models.BooleanField(default=True)),
                ('current_avatar', models.ForeignKey(blank=True, help_text='El avatar que el usuario está usando actualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users_profile', to='api.avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="La palabra o frase en inglés (e.g. 'Give up')", max_length=200, unique=True)),
                ('translation', models.CharField(blank=True, help_text="Traducción directa al español (e.g. 'Rendirse')", max_length=200, null=True)),
                ('definition', models.TextField(help_text="Explicación en inglés (e.g. 'To stop trying to do something')")),
                ('word_type', models.CharField(choices=[('PHRASAL_VERB', 'Phrasal Verb'), ('SLANG', 'Slang'), ('IDIOM', 'Idiom'), ('VOCABULARY', 'Vocabulary')], default='SLANG', max_length=50)),
                ('examples', models.JSONField(default=list, help_text="Lista de diccionarios. Claves obligatorias: 'en' y 'es'.")),
                ('difficulty_level', models.IntegerField(default=1, help_text='1: Principiante, 10: Experto (Usado para filtrar qué palabras salen según el nivel del usuario)')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas. Usadas para encontrar distractores del mismo tema.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('substitutes', models.ManyToManyField(blank=True, help_text='Sinónimos aceptados en los quizzes de escritura.', to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('words_seen_total', models.IntegerField(default=0)),
                ('slangs_seen', models.IntegerField(default=0)),
                ('phrasal_verbs_seen', models.IntegerField(default=0)),
                ('correct_answers_total', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('correct_slangs', models.IntegerField(default=0)),
                ('total_slangs_questions', models.IntegerField(default=0)),
                ('correct_phrasal_verbs', models.IntegerField(default=0)),
                ('total_phrasal_verbs_questions', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, related_name='unlocked_by_users', to='api.badge')),
                ('unlocked_avatars', models.ManyToManyField(blank=True, help_text='Avatares que el usuario ha desbloqueado.', related_name='unlocked_by_users', to='api.avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
                ('unlocked_words', models.ManyToManyField(blank=True, help_text='Palabras que el usuario ya ha visto en el juego', related_name='unlocked_by_users', to='api.word')),
            ],
        ),
    ]
