# Generated by Django 5.2.3 on 2025-06-13 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre de la insignia.', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Descripción de lo que se necesita para obtenerla.')),
                ('image', models.ImageField(blank=True, help_text='Imagen de la insignia.', null=True, upload_to='badges/')),
                ('category', models.CharField(choices=[('BASIC', 'Básica'), ('RARE', 'Rara'), ('EPIC', 'Épica'), ('LEGENDARY', 'Legendaria')], default='BASIC', max_length=20)),
                ('condition_description', models.TextField(help_text="Descripción legible de la condición (e.g., 'Acertar 10 slangs').")),
                ('reward_description', models.TextField(help_text="Descripción de la recompensa (e.g., '+30 EXP, Nuevo Avatar').")),
                ('reward_data', models.JSONField(blank=True, default=dict, help_text="Datos programáticos para las recompensas (e.g., {'exp': 30, 'avatar_id': 5}).")),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('correct_in_game', models.IntegerField(default=0)),
                ('total_questions_in_game', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('words_seen_total', models.IntegerField(default=0)),
                ('slangs_seen', models.IntegerField(default=0)),
                ('phrasal_verbs_seen', models.IntegerField(default=0)),
                ('correct_answers_total', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('correct_slangs', models.IntegerField(default=0)),
                ('total_slangs_questions', models.IntegerField(default=0)),
                ('correct_phrasal_verbs', models.IntegerField(default=0)),
                ('total_phrasal_verbs_questions', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, related_name='unlocked_by_users', to='api.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='El slang o phrasal verb en sí.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Definición clara y concisa de la palabra o frase.')),
                ('word_type', models.CharField(choices=[('SLANG', 'Jergas'), ('PHRASAL_VERB', 'Verbos Frasales'), ('NONE', 'Ninguno')], default='NONE', help_text='Define si es un slang o un phrasal verb.', max_length=20)),
                ('examples', models.JSONField(blank=True, default=list, help_text='Lista de ejemplos de uso.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty_level', models.IntegerField(default=1, help_text='Nivel de dificultad de la palabra (1-5, por ejemplo).')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista de etiquetas para la palabra.')),
                ('substitutes', models.ManyToManyField(blank=True, related_name='related_to', to='api.word')),
            ],
        ),
    ]
