# Generated by Django 6.0.2 on 2026-03-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='bosses_killed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='letters_killed',
            field=models.IntegerField(default=0),
        ),
    ]
