# Generated by Django 5.2.3 on 2025-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition_description',
            field=models.TextField(help_text="Descripción legible de la condición (e.g., 'Acertar 10 slangs')"),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(help_text='Descripción de lo que se necesita para obtenerla'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen de la insignia', null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='reward_data',
            field=models.JSONField(blank=True, default=dict, help_text="Datos programáticos para las recompensas (e.g., {'exp': 30, 'avatar_id': 5})"),
        ),
        migrations.AlterField(
            model_name='badge',
            name='reward_description',
            field=models.TextField(help_text="Descripción de la recompensa (e.g., '+30 EXP, Nuevo Avatar')"),
        ),
        migrations.AlterField(
            model_name='badge',
            name='title',
            field=models.CharField(help_text='Nombre de la insignia', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Correo electrónico ya existe'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(help_text='Definición clara y concisa de la palabra o frase'),
        ),
        migrations.AlterField(
            model_name='word',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='Nivel de dificultad de la palabra (1-5, por ejemplo)'),
        ),
        migrations.AlterField(
            model_name='word',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='Lista de ejemplos de uso'),
        ),
        migrations.AlterField(
            model_name='word',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de etiquetas para la palabra'),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(help_text='El slang o phrasal verb en sí', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('SLANG', 'Jergas'), ('PHRASAL_VERB', 'Verbos Frasales'), ('NONE', 'Ninguno')], default='NONE', help_text='Define si es un slang o un phrasal verb', max_length=20),
        ),
    ]
