# Generated by Django 6.0.2 on 2026-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gamehistory_bosses_killed_gamehistory_letters_killed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='total_bosses_killed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_letters_killed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_time_played_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
