# Generated by Django 5.2.3 on 2025-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_is_online_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
