# Generated by Django 6.0.2 on 2026-03-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userstats_total_bosses_killed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_title',
            field=models.CharField(blank=True, help_text='Título que el usuario está usando actualmente.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='unlocked_titles',
            field=models.JSONField(blank=True, default=list, help_text='Títulos que el usuario ha desbloqueado.'),
        ),
    ]
