# Generated by Django 5.2.3 on 2025-07-03 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(help_text='Imagen del avatar', upload_to='avatars/')),
                ('is_default', models.BooleanField(default=False, help_text='Si es un avatar disponible para todos al inicio')),
                ('unlock_condition_description', models.TextField(blank=True, help_text='Descripción de cómo desbloquearlo si no es default', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='unlock_condition_data',
            field=models.JSONField(blank=True, default=dict, help_text="Datos programáticos para las condiciones de desbloqueo (e.g., {'type': 'correct_slangs', 'value': 10})"),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_avatar',
            field=models.ForeignKey(blank=True, help_text='El avatar que el usuario está usando actualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users_profile', to='api.avatar'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='unlocked_avatars',
            field=models.ManyToManyField(blank=True, help_text='Avatares que el usuario ha desbloqueado.', related_name='unlocked_by_users', to='api.avatar'),
        ),
    ]
