# Generated by Django 6.0.2 on 2026-03-06 19:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_current_title_userstats_unlocked_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(help_text='Imagen del avatar', upload_to=api.models.avatar_image_upload_to),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen de la insignia', null=True, upload_to=api.models.badge_image_upload_to),
        ),
    ]
