# Generated by Django 5.2.3 on 2025-07-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_avatar_badge_unlock_condition_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='unlock_condition_data',
            field=models.JSONField(blank=True, default=list, help_text="Lista de objetos de condición (e.g., [{'type': 'correct_slangs', 'value': 10}])"),
        ),
    ]
