# Generated by Django 6.0.2 on 2026-03-07 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_avatar_image_alter_badge_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='total_phrasal_verbs_questions',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='total_slangs_questions',
        ),
    ]
