# Generated by Django 6.0.2 on 2026-03-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_redundant_question_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografía del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nombre completo del usuario', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatars/default.jpg', help_text='Imagen del perfil', null=True, upload_to='avatars/'),
        ),
    ]
