# Generated by Django 6.0.2 on 2026-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_badge_unlock_condition_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='game_mode',
            field=models.CharField(choices=[('SURVIVOR', 'Survivor RPG (Godot)'), ('QUIZ', 'Lección Interactiva (React)')], default='QUIZ', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, help_text="Traducción directa (e.g. 'Rendirse')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(help_text='Definición en inglés o explicación de uso'),
        ),
        migrations.AlterField(
            model_name='word',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='1: Fácil, 10: Difícil'),
        ),
        migrations.AlterField(
            model_name='word',
            name='examples',
            field=models.JSONField(default=list, help_text="Lista de objetos con claves 'en' (inglés) y 'es' (español)"),
        ),
        migrations.AlterField(
            model_name='word',
            name='substitutes',
            field=models.ManyToManyField(blank=True, help_text='Palabras con significado similar aceptadas como respuesta', to='api.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por coma para agrupar temas', max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(help_text="La palabra o frase en inglés (e.g. 'Give up')", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('PHRASAL_VERB', 'Phrasal Verb'), ('SLANG', 'Slang')], default='SLANG', max_length=50),
        ),
    ]
