# Generated by Django 6.0.2 on 2026-02-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_word_updated_at_gamehistory_game_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='unlocked_words',
            field=models.ManyToManyField(blank=True, help_text='Palabras que el usuario ya ha visto en el juego', related_name='unlocked_by_users', to='api.word'),
        ),
    ]
