# Generated by Django 6.0.2 on 2026-09-07 15:34

import api.models
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(help_text='Imagen del avatar', upload_to=api.models.avatar_image_upload_to, validators=[api.validators.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen de la insignia', null=True, upload_to=api.models.badge_image_upload_to, validators=[api.validators.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatars/default.jpg', help_text='Imagen del perfil', null=True, upload_to='avatars/', validators=[api.validators.validar_tamano_imagen]),
        ),
    ]
